language: c
notifications:
   slack: skydreams:1FLUnEeqaNLinKq1p0lJf9F5
branches:
 only:
  - master
services:
 - docker
env:
script: free && echo && df -k  && sudo ls  -ltd /var/lib/docker && sudo du -ks /var/lib/docker &&  sudo ./relibdo.sh
